### ISSUE TITLE
Добавить PMD-плагин

### ISSUE THREAD

**Issue by AlexanderBobryakov** [KruASe76/news-recommendation-service#2]
TO-BE:
- Плагин https://docs.gradle.org/current/userguide/pmd_plugin.html
- Проверить, что он запускается при build проекта и проверяет правильность написания кода (для эксперимента можно допустить какую-нибудь ошибку)
- Оповестить команду об этом плагине

**Comment by AlexanderBobryakov** [comment]
В коде остался sout, на который pmd-плагин должен ругаться. На данный момент в проекте pmd работает в минимальном составе, необходимо добавить существующие ruleSets (как минимум category/java/bestpractices.xml), см https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.PmdExtension.html

Также все мр нужно скидывать на ревью, а не просто закрывать. Мне нужно оценивать работу каждого члена команды на протяжении всей работы

**Comment by KruASe76** [comment]
> необходимо добавить существующие ruleSets

окей, сейчас сделаю


> Также все мр нужно скидывать на ревью, а не просто закрывать.

то есть всегда ставить тебя единственным ревьювером?

**Comment by AlexanderBobryakov** [comment]
> то есть всегда ставить тебя единственным ревьювером?

В идеале, чтобы все члены команды смотрели пулреквесты и ставили апрувы, но тут смотрите по вашей загрузке. Меня точно нужно в ревьюверы
