### ISSUE TITLE
DB. Поднять PosgreSQL в Docker

### ISSUE THREAD

**Issue by AlexanderBobryakov** [KruASe76/news-recommendation-service#3]
TO-BE:
- В корне репозитория создать директорию docker-compose
- Создать внутри файл docker-compose.yml
- Установить docker desktop
- Добавить в docker-compose.yml поднятие БД PostgreSQL. Пример - https://habr.com/ru/articles/578744/
- Добавить инструкцию в readme по запуску и примеру работы (скрипты, подключение, что/где посмотреть)

**Comment by KruASe76** [comment]
решил создать отдельный `docker/README.md`, чтобы не засорять основной иструкциями
