### ISSUE TITLE
Парсер RSS

### ISSUE THREAD

**Issue by AlexanderBobryakov** [KruASe76/news-recommendation-service#9]
TO-BE:
- В дальшнейших задачах нужно будет реализовать парсинг разных сайтов. Отдельный java-класс будет
    для отдельного парсера
- Нужно создать общий внутренний java-интерфейс для этих парсеров, например:
```java
public interface SiteParse {
    List<Article> parseLastArticles();
}
```
Метод будет возвращать DTO-объект Article. Нужно определить в нем перечень полей
(название, описание, дата публикации, ссылка и тд)
- Дальнейшие парсеры будут реализовывать эти интерфейсы для каждого отбельного сайта

**Comment by KruASe76** [comment]
upd:
реализуем универсальный парсер для протокола RSS
